Remove outdated DIND stuff

diff --git a/image/base/wrapdocker b/image/base/wrapdocker
--- a/image/base/wrapdocker
+++ b/image/base/wrapdocker
@@ -1,10 +1,14 @@
 #!/bin/bash
 
-# Copyright 2013-2015 Jérôme Petazzoni, Johan Haleby, lalyos, James Harris,
+# Copyright 2013-2016 Jérôme Petazzoni, Johan Haleby, lalyos, James Harris,
 #                     Michael Elsdörfer, Tony Hesjevik, Esben Haabendal,
-#                     Michael A. Smith, Stefan Schimanski, Karl Isenberg
+#                     Michael A. Smith, Stefan Schimanski, Karl Isenberg,
+#                     Alexander Morozov, David Calavera, Sven Dowideit,
+#                     Tianon Gravi, Maru Newby
 #
-# Original source: https://github.com/jpetazzo/dind
+# Original sources: https://github.com/jpetazzo/dind
+#                   https://github.com/docker/docker/blob/master/hack/dind
+#                   https://github.com/marun/dkr-systemd-dind
 # Modified to add docker network reservations.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
@@ -19,90 +23,32 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
+set -o errexit
+set -o nounset
+set -o pipefail
+
 # Ensure that all nodes in /dev/mapper correspond to mapped devices currently loaded by the device-mapper kernel driver
 dmsetup mknodes
 
-# First, make sure that cgroups are mounted correctly.
-CGROUP=/sys/fs/cgroup
-: {LOG:=stdio}
-
-[ -d $CGROUP ] ||
-  mkdir $CGROUP
-
-mountpoint -q $CGROUP ||
-  mount -n -t tmpfs -o uid=0,gid=0,mode=0755 cgroup $CGROUP || {
-    echo "Could not make a tmpfs mount. Did you use --privileged?"
-    exit 1
-  }
-
 if [ -d /sys/kernel/security ] && ! mountpoint -q /sys/kernel/security; then
   mount -t securityfs none /sys/kernel/security || {
-    echo "Could not mount /sys/kernel/security."
-    echo "AppArmor detection and --privileged mode might break."
+    echo >&2 'Could not mount /sys/kernel/security.'
+    echo >&2 'AppArmor detection and --privileged mode might break.'
   }
 fi
 
-# Mount the cgroup hierarchies exactly as they are in the parent system.
-for SUBSYS in $(cut -d: -f2 /proc/1/cgroup); do
-  [ -d $CGROUP/$SUBSYS ] || mkdir $CGROUP/$SUBSYS
-  mountpoint -q $CGROUP/$SUBSYS ||
-    mount -n -t cgroup -o $SUBSYS cgroup $CGROUP/$SUBSYS
+# Ensure shared mount propagation to ensure volume mounting works for
+# Kubernetes and OpenShift.
+mount --make-shared /
 
-  # The two following sections address a bug which manifests itself
-  # by a cryptic "lxc-start: no ns_cgroup option specified" when
-  # trying to start containers withina container.
-  # The bug seems to appear when the cgroup hierarchies are not
-  # mounted on the exact same directories in the host, and in the
-  # container.
-
-  # Named, control-less cgroups are mounted with "-o name=foo"
-  # (and appear as such under /proc/<pid>/cgroup) but are usually
-  # mounted on a directory named "foo" (without the "name=" prefix).
-  # Systemd and OpenRC (and possibly others) both create such a
-  # cgroup. To avoid the aforementioned bug, we symlink "foo" to
-  # "name=foo". This shouldn't have any adverse effect.
-
-  # the || true prevents the following error to quit (see https://github.com/jpetazzo/dind/pull/84#issuecomment-134236303):
-  # ln: failed to create symbolic link '/sys/fs/cgroup/systemd/name=systemd': Operation not permitted
-  echo $SUBSYS | grep -q ^name= && {
-    NAME=$(echo $SUBSYS | sed s/^name=//)
-    ln -s $SUBSYS $CGROUP/$NAME || true
-  }
-
-  # Likewise, on at least one system, it has been reported that
-  # systemd would mount the CPU and CPU accounting controllers
-  # (respectively "cpu" and "cpuacct") with "-o cpuacct,cpu"
-  # but on a directory called "cpu,cpuacct" (note the inversion
-  # in the order of the groups). This tries to work around it.
-  [ $SUBSYS = cpuacct,cpu ] && ln -s $SUBSYS $CGROUP/cpu,cpuacct
-done
-
-# Note: as I write those lines, the LXC userland tools cannot setup
-# a "sub-container" properly if the "devices" cgroup is not in its
-# own hierarchy. Let's detect this and issue a warning.
-grep -q :devices: /proc/1/cgroup ||
-  echo "WARNING: the 'devices' cgroup should be in its own hierarchy."
-grep -qw devices /proc/1/cgroup ||
-  echo "WARNING: it looks like the 'devices' cgroup is not mounted."
-
-# Now, close extraneous file descriptors.
-pushd /proc/self/fd >/dev/null
-for FD in *; do
-  case "$FD" in
-  # Keep stdin/stdout/stderr
-  [012])
-    ;;
-  # Nuke everything else
-  *)
-    eval exec "$FD>&-"
-    ;;
-  esac
-done
-popd >/dev/null
+# Mount /tmp (conditionally)
+if ! mountpoint -q /tmp; then
+  mount -t tmpfs none /tmp
+fi
 
 # find supported filesystem to use for docker image mounts
 if grep -q overlay /proc/filesystems; then
-  STORAGE_FS=overlay
+  STORAGE_FS=overlay2
 elif grep -q aufs /proc/filesystems; then
   STORAGE_FS=aufs
 else
@@ -124,7 +70,7 @@ mkdir -p "${STORAGE_DIR}"
 # probably 3.19). On those it's possible to mount an overlay in an overlay, but
 # writing to a file results in a "No device" error.
 OVERLAY_WORKS=true
-if [ "${STORAGE_FS}" = "overlay" ]; then
+if [ "${STORAGE_FS}" = "overlay2" ]; then
   D="${STORAGE_DIR}/smoke"
   mkdir -p "${D}/upper" "${D}/lower" "${D}/work" "${D}/mount"
 
@@ -138,7 +84,7 @@ fi
 # If another filesystem than overlay is used or overlay does not work, create
 # an ext3 loop device as an intermediary layer. The max size of the loop device
 # is $VAR_LIB_DOCKER_SIZE in GB (default=5).
-if [ "${STORAGE_FS}" != "overlay" -o "${OVERLAY_WORKS}" == false ]; then
+if [ "${STORAGE_FS}" != "overlay2" -o "${OVERLAY_WORKS}" == false ]; then
   STORAGE_FILE="/data/docker"
   VAR_LIB_DOCKER_SIZE=${VAR_LIB_DOCKER_SIZE:-5}
   mkdir -p "$(dirname "${STORAGE_FILE}")"
@@ -152,11 +98,9 @@ fi
 # bind mount it back to /var/lib/docker
 mount -o bind "${STORAGE_DIR}" /var/lib/docker
 
-DOCKER_DAEMON_ARGS="${DOCKER_DAEMON_ARGS:-} --storage-driver=${STORAGE_FS} --log-driver=json-file"
+export DOCKER_DAEMON_ARGS="${DOCKER_DAEMON_ARGS:-} --storage-driver=${STORAGE_FS} --log-driver=json-file"
 
-# If a pidfile is still around (for example after a container restart),
-# delete it so that docker can start.
-rm -rf /var/run/docker.pid
+docker_net_opts=""
 
 # Bridge the containerized docker network to the host docker network.
 # To enable this bridge, specify an IP offset for this container to use.
@@ -200,33 +144,30 @@ if [ ! -z "${DOCKER_NETWORK_OFFSET:-}" ]; then
 
   # let docker reuse the given IP. If you run more than one dind slave, add
   # --fixed-cidr=a.b.c.d/24 to DOCKER_DAEMON_ARGS with disjunct networks.
-  DOCKER_DAEMON_ARGS="${DOCKER_DAEMON_ARGS} --bip=${IP_CIDR} --fixed-cidr=${FIXED_CIDR}"
+  docker_net_opts="${docker_net_opts} --bip=${IP_CIDR} --fixed-cidr=${FIXED_CIDR}"
+  export DOCKER_DAEMON_ARGS="${DOCKER_DAEMON_ARGS} --bip=${IP_CIDR} --fixed-cidr=${FIXED_CIDR}"
 
   # delete incompatible network settings
   rm -rf "/var/lib/docker/network"
 fi
 
-# stop docker daemon on shutdown to avoid loopback leaks
-trap "service docker stop" EXIT
+# FIXME: the following should be in systemd image
+if [[ "${docker_net_opts}" ]]; then
+  # only do this when starting the actual cluster and not during initial image preparation
 
-# start docker daemon
-if docker daemon --help &>/dev/null; then
-  DOCKER_DAEMON="docker daemon"
-else
-  DOCKER_DAEMON="docker -d"
-fi
-if [ "$LOG" == "file" ]; then
-  ${DOCKER_DAEMON} ${DOCKER_DAEMON_ARGS} &>/var/log/docker.log &
-else
-  ${DOCKER_DAEMON} ${DOCKER_DAEMON_ARGS} &
-fi
-(( timeout = 60 + SECONDS ))
-until docker info >/dev/null 2>&1; do
-  if (( SECONDS >= timeout )); then
-    echo 'Timed out trying to connect to internal docker host.' >&2
-    exit 1
+  # FIXME: pass other options to docker started via systemd, too
+  if [ -f /lib/systemd/system/docker.service ]; then
+    sed -i "s@\(ExecStart=.*\)@\1 ${docker_net_opts}@" /lib/systemd/system/docker.service
   fi
-  sleep 1
-done
-[[ $1 ]] && exec "$@"
-exec bash --login
+
+  # FIXME: the following should be in systemd image
+  # This ensures that node names are IPs so we don't need dnsmasq
+  # FIXME: put proper dns / domain from config.sh there (KUBELET_DNS_ARGS)
+  if [ -f /etc/systemd/system/kubelet.service.d/10-kubeadm.conf ]; then
+    hostname_override="$(getent hosts $(hostname) | cut -d' ' -f1 | sort -u | tail -1)"
+    sed -i "s@\(KUBELET_EXTRA_ARGS=\)@\1--hostname-override=${hostname_override} @" \
+        /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
+  fi
+fi
+
+exec "$@"
