Fix race & improve diagnostics on service startup

diff --git a/image/systemd/start_services b/image/systemd/start_services
--- a/image/systemd/start_services
+++ b/image/systemd/start_services
@@ -24,8 +24,6 @@ EOF
   fi
 fi
 
-systemctl daemon-reload
-
 # wait for systemd to start in the container
 (( timeout = 60 + SECONDS ))
 until systemctl status >/dev/null 2>&1; do
@@ -36,8 +34,16 @@ until systemctl status >/dev/null 2>&1; do
   sleep 1
 done
 
+systemctl daemon-reload
+
 if [ "${1:-}" = "docker" ]; then
     systemctl stop docker
 fi
 
-systemctl start "$@"
+for service in "$@"; do
+    if ! systemctl start "${service}"; then
+        echo >&2 "${service} failed to start. Diagnostics below:"
+        systemctl status "${service}"
+        exit 1
+    fi
+done
