Add IPv6 only support to DinD
This commit adds support for IPv6 only mode for a Kubernetes cluster used with DinD.
To do this, it uses bind9 for DNS32, and Tayga for NAT64. Intention here, is so that
this can be used for E2E testing, where we have an IPv6 only cluster, but is connected
to an IPv4 only network (e.g. running on Google Compute Engine VM).

Notes:
- Uses /80 pod network that is contained within DinD subnet (like done for v4).
- Several environment variables can be used to customize.
- Uses new CNI 0.6.0 plugin.
- Uses Tagya container (built by Daneyon Hansen) for NAT64 (include into DinD build?).
- Forces all external DNS lookups to return A record, and will build an IPv4 embedded
  IPv6 address to refer to the node.
- NAT64 requires static route on host, which is added (using sudo) by script,
  if missing. Can be set up in advance, if desired.
- Allows DNS server to be specified for forwarded requests, in case in an environment
  where host doesn't allow forwarding to DNS servers outside of corporate network.
- Since not released, one needs to build and run with local DinD image.
- README suggests in-flight IPv6 patches and work-arounds for proper IPv6 operation.
- Includes fix to issue where failure to stop kube-dns or proxy pods does not restore
  the controller manifest.
- IPv4 mode should work the same as before, only using new CNI plugin.
- Added src-working-area test case to test.sh to allow testing of DinD with local
 Kubernetes repo.
- Hairpin mode enabled for CNI plugin (precludes IPv6 DAD, until kernel is updated).
- Temp change to Kubernetes to prevent conntrack setting changes, based on bug 50787.

Questions:
- Is there a way to create static route on host w/o sudo for NAT64 server?

Issues:
- Sometimes see etcdserver timeouts during cluster bring up (not on all systems).
- Retries, which do kubeadm resets, seem to cause removal of files.
- Once kube-proxy is modified to allow conntrack settings override, DinD will need
  to be abled to modify the kube-proxy config file.

TODOs:
- Verify on GCE using gce-setup.sh (having issues as no released image to use).
- Look at CI failures (working with changeset + kubernetes w/IPv6 changes, not
  tested for older images).
- Pull CNI plugin install, once CNI 0.6.0 plugin is part of Kubernetes.

FUTURES:
- Dual stack.
- IPv6 only (externally as well). Currently, github.com doesn't support IPv6.
- Pod subnet exclusive of DinD subnet.
- NAT66 container could be used for pure IPv6 or dual stack environment (along with
  DNS64 config change).

diff --git a/image/dindnet b/image/dindnet
--- a/image/dindnet
+++ b/image/dindnet
@@ -18,51 +18,86 @@ set -o nounset
 set -o pipefail
 set -o errtrace
 
-IP_CIDR=$(ip addr show eth0 | grep -w inet | awk '{ print $2; }')
-IP=$(echo $IP_CIDR | sed 's,/.*,,')
+
+IPV4_CIDR="$(ip addr show eth0 | grep -w inet | awk '{ print $2; }')"
+IPV4="$(echo ${IPV4_CIDR} | sed 's,/.*,,')"
 
 function dind::setup-bridge {
   # create dind0 bridge and attach it to the veth interface eth0
   brctl addbr dind0
   brctl addif dind0 eth0
   ip link set dind0 up
+
+  # Save route, before delete IPv4 address, which will remove route
+  DEFAULT_GW="$(ip route | grep default | cut -f 3 -d" ")"
+  ip addr del ${IPV4_CIDR} dev eth0
+  if [[ "${IP_MODE}" != "ipv6" ]]; then
+    ip addr add ${IPV4_CIDR} dev dind0
+    ip route add default via ${DEFAULT_GW} dev dind0
+  else  # IPv6 only
+    DEFAULT_GW="$(ip -6 route | grep default | cut -f 3 -d" ")"
+    IPV6_CIDR="$(ip addr show eth0 | grep -w inet6 | grep -i global | head -1 | awk '{ print $2; }')"
+    IPV6="$(echo ${IPV6_CIDR} | sed 's,/.*,,')"
+    ip addr del ${IPV6_CIDR} dev eth0
+    ip addr add ${IPV6_CIDR} dev dind0
+    if [[ ! -z "${DEFAULT_GW}" ]]; then
+      # Must remove old route first (not deleted, when delete IP off of eth0, like with V4)
+      ip -6 route del default via ${DEFAULT_GW} dev eth0
+      ip -6 route add default via ${DEFAULT_GW} dev dind0
+    fi
+    ip -6 route add ${DNS64_PREFIX_CIDR} via ${LOCAL_NAT64_SERVER}
+  fi
+}
+
+function dind::setup-config-file {
+  if [[ ${IP_MODE} = "ipv6" ]]; then
+    INSTANCE=`hostname | cut -d"-" -f 3`
+    if [[ "${INSTANCE}" = "" ]]; then
+      INSTANCE="10"
+    fi
+    echo "Instance: ${INSTANCE}"
+
+    # FUTURE: Handle dual-stack mode
   
-  # move ip to the bridge and restore routing via the old gateway
-  NETWORK_SIZE=$(echo $IP_CIDR | sed 's,.*/,,')
-  DEFAULT_ROUTE=$(ip route | grep default | sed 's/eth0/dind0/')
-  DEFAULT_GW=$(echo $DEFAULT_ROUTE|awk '{print $3;}')
+    NETWORK="$(echo $DEFAULT_GW | sed 's/[:][^:]*$/:/')"
+    NETWORK_SIZE="$(echo ${IPV6_CIDR} | sed 's,.*/,,')"
+    # Will use /80 for pod network
+    HOST_MIN="${POD_NET_PREFIX}:${INSTANCE}::1"
+    HOST_MAX="${POD_NET_PREFIX}:${INSTANCE}:ffff:ffff:ffff"
+    DEFAULT_ROUTE="::/0"
+  else
+    # compute a network for the containers to live in
+    # by adding CNI_BRIDGE_NETWORK_OFFSET to the current IP and cutting off
+    # non-network bits according to CNI_BRIDGE_NETWORK_SIZE
+    CNI_BRIDGE_NETWORK_SIZE="${CNI_BRIDGE_NETWORK_SIZE:-24}"
+    NETWORK="$(ip route | grep dind0 | grep -v default | sed 's,/.*,,')"
+    NETWORK_SIZE="$(echo ${IPV4_CIDR} | sed 's,.*/,,')"
   
-  ip addr del $IP_CIDR dev eth0
-  ip addr add $IP_CIDR dev dind0
-  ip route add $DEFAULT_ROUTE
+    WILDCARD=$(ipcalc ${IPV4_CIDR} | grep Wildcard | awk '{print $2;}')
+    IFS=. read -r i1 i2 i3 i4 <<< ${IPV4}
+    IFS=. read -r n1 n2 n3 n4 <<< ${NETWORK}
+    IFS=. read -r o1 o2 o3 o4 <<< ${CNI_BRIDGE_NETWORK_OFFSET}
+    IFS=. read -r w1 w2 w3 w4 <<< ${WILDCARD}
   
-  # compute a network for the containers to live in
-  # by adding CNI_BRIDGE_NETWORK_OFFSET to the current IP and cutting off
-  # non-network bits according to CNI_BRIDGE_NETWORK_SIZE
-  CNI_BRIDGE_NETWORK_SIZE=${CNI_BRIDGE_NETWORK_SIZE:-24}
-  NETWORK=$(ip route | grep dind0 | grep -v default | sed 's,/.*,,')
+    IP_PLUS_OFFSET=$(printf "%d.%d.%d.%d\n" \
+                            "$(( n1 + ((i1 - n1 + o1) & w1) ))" \
+                            "$(( n2 + ((i2 - n2 + o2) & w2) ))" \
+                            "$(( n3 + ((i3 - n3 + o3) & w3) ))" \
+                            "$(( n4 + ((i4 - n4 + o4) & w4) ))")
   
-  WILDCARD=$(ipcalc $IP_CIDR | grep Wildcard | awk '{print $2;}')
-  IFS=. read -r i1 i2 i3 i4 <<< ${IP}
-  IFS=. read -r n1 n2 n3 n4 <<< ${NETWORK}
-  IFS=. read -r o1 o2 o3 o4 <<< ${CNI_BRIDGE_NETWORK_OFFSET}
-  IFS=. read -r w1 w2 w3 w4 <<< ${WILDCARD}
-  
-  IP_PLUS_OFFSET=$(printf "%d.%d.%d.%d\n" \
-                          "$(( n1 + ((i1 - n1 + o1) & w1) ))" \
-                          "$(( n2 + ((i2 - n2 + o2) & w2) ))" \
-                          "$(( n3 + ((i3 - n3 + o3) & w3) ))" \
-                          "$(( n4 + ((i4 - n4 + o4) & w4) ))")
-  
-  HOST_MIN=$(ipcalc $IP_PLUS_OFFSET/$CNI_BRIDGE_NETWORK_SIZE | grep HostMin | awk '{print $2;}')
-  HOST_MAX=$(ipcalc $IP_PLUS_OFFSET/$CNI_BRIDGE_NETWORK_SIZE | grep HostMax | awk '{print $2;}')
+    HOST_MIN=$(ipcalc ${IP_PLUS_OFFSET}/${CNI_BRIDGE_NETWORK_SIZE} | grep HostMin | awk '{print $2;}')
+    HOST_MAX=$(ipcalc ${IP_PLUS_OFFSET}/${CNI_BRIDGE_NETWORK_SIZE} | grep HostMax | awk '{print $2;}')
+    DEFAULT_ROUTE="0.0.0.0/0"
+  fi
   echo "Using ${HOST_MIN} .. ${HOST_MAX} for docker containers"
-  
-  cat >/etc/cni/net.d/cni.conf <<EOF
+  CONFIG_FILE="/etc/cni/net.d/cni.conf"
+  cat >${CONFIG_FILE} <<CFG_PREFIX_EOF
 {
+    "cniVersion": "0.3.0",
     "name": "dindnet",
     "type": "bridge",
     "bridge": "dind0",
+    "hairpinMode": true,
     "ipam": {
         "type": "host-local",
         "subnet": "${NETWORK}/${NETWORK_SIZE}",
@@ -70,29 +105,72 @@ function dind::setup-bridge {
         "rangeEnd": "${HOST_MAX}",
         "gateway": "${DEFAULT_GW}",
         "routes": [
-            { "dst": "0.0.0.0/0" }
+CFG_PREFIX_EOF
+  if [[ ${IP_MODE} = "ipv6" ]]; then
+      cat >>${CONFIG_FILE} <<CFG_IPV6_EOF
+            { "dst": "${DNS64_PREFIX_CIDR}", "gw": "${LOCAL_NAT64_SERVER}"},
+CFG_IPV6_EOF
+  fi
+  cat >>${CONFIG_FILE} <<CFG_SUFFIX_EOF
+            { "dst": "${DEFAULT_ROUTE}" }
         ]
     }
 }
-EOF
+CFG_SUFFIX_EOF
+  echo "Config file created: ${CONFIG_FILE}"
 }
 
+function dind::make-kubelet-extra-dns-args {
+  # Create drop-in file here, where we know the DNS IP.
+  mkdir -p /etc/systemd/system/kubelet.service.d
+  cat >/etc/systemd/system/kubelet.service.d/20-extra-dns-args.conf <<EOF
+[Service]
+Environment="KUBELET_DNS_ARGS=--cluster-dns=${DNS_SVC_IP} --cluster-domain=cluster.local"
+EOF
+  # Unconditionally set for both IPv4 and IPv6 mode
+}
+
+
 if [[ "${CNI_BRIDGE_NETWORK_OFFSET:-}" ]]; then
-   dind::setup-bridge
+  dind::setup-bridge
+  # TODO: Remove, once DinD is able to use v0.6.0 CNI release
+  protocol=""
+  if [[ ${IP_MODE} = "ipv6" ]]; then
+      protocol="-6"
+  fi
+  curl -sSL ${protocol} --retry 5 https://github.com/containernetworking/plugins/releases/download/v0.6.0/cni-plugins-amd64-v0.6.0.tgz | \
+      tar -C /opt/cni/bin -xz
+  dind::setup-config-file
+  dind::make-kubelet-extra-dns-args
 fi
 
-# make docker's kube-dns friendly
-old_ns="$(awk '/^nameserver/ {print $2; exit}' /etc/resolv.conf)"
-if [[ ${old_ns} ]]; then
-  # sed -i doesn't work here because of docker's handling of /etc/resolv.conf
-  sed "s/^nameserver.*/nameserver ${IP}/" /etc/resolv.conf >/etc/resolv.conf.updated
+if [[ ${IP_MODE} = "ipv6" ]]; then
+  sed -e "s/^${IPV4}/${IPV6}/g" /etc/hosts > /etc/hosts.updated
+  cp /etc/hosts /etc/hosts.orig
+  cat /etc/hosts.updated >/etc/hosts
+  # Removed embedded docker DNS, as we'll only be using IPv6, which is already in resolv.conf
+  sed "s/^nameserver.*127\.0\.0\.11/# Removed 127.0.0.11/" /etc/resolv.conf >/etc/resolv.conf.updated
+  cp /etc/resolv.conf /etc/resolv.conf.orig
   cat /etc/resolv.conf.updated >/etc/resolv.conf
-  # rm /tmp/resolv.conf.updated
+  echo "Setup completed"
+  set +x
   while true; do
-    socat udp4-recvfrom:53,reuseaddr,fork,bind=${IP} UDP:${old_ns}:53 || true
-    echo "WARNING: restarting socat" >&2
+      sleep 1  # Keep service running, so actions not attempted multiple times
   done
 else
-  echo "WARNING: couldn't get nameserver" >&2
-  exit 1  
+  # make docker's kube-dns friendly
+  old_ns="$(awk '/^nameserver/ {print $2; exit}' /etc/resolv.conf)"
+  if [[ ${old_ns} ]]; then
+    # sed -i doesn't work here because of docker's handling of /etc/resolv.conf
+    sed "s/^nameserver.*/nameserver ${IPV4}/" /etc/resolv.conf >/etc/resolv.conf.updated
+    cp /etc/resolv.conf /etc/resolv.conf.orig
+    cat /etc/resolv.conf.updated >/etc/resolv.conf
+    while true; do
+      socat udp4-recvfrom:53,reuseaddr,fork,bind=${IPV4} UDP:${old_ns}:53 || true
+      echo "WARNING: restarting socat" >&2
+    done
+  else
+    echo "WARNING: couldn't get nameserver" >&2
+    exit 1
+  fi
 fi
