Fix race condition due to apiserver restart

diff --git a/image/wrapkubeadm b/image/wrapkubeadm
--- a/image/wrapkubeadm
+++ b/image/wrapkubeadm
@@ -277,8 +277,19 @@ function dind::frob-proxy {
 }
 
 function dind::frob-apiserver {
+  local cur_pid=$(pidof kube-apiserver)
   local -a filters=("${mount_binaries}" "${apiserver_insecure_bind_address}" "${apiserver_insecure_bind_port}" "${apiserver_mount_propagation}")
   dind::frob-file "${apiserver_static_pod}" "${filters[@]}"
+  # Make sure apiserver really restarts before continuing, otherwise
+  # we may run into a situation where it restarts while kube-proxy is
+  # being patched.
+  local n=60
+  while [[ $(pidof kube-apiserver) = ${cur_pid} ]]; do
+    if ((--n == 0)); then
+      echo "Error: timed out waiting for apiserver to restart" >&2
+    fi
+    sleep 0.5
+  done
 }
 
 function dind::frob-scheduler {
@@ -297,10 +308,7 @@ function dind::wait-for-apiserver {
     local docker_ip="$(ip addr show docker0 | grep -w inet | awk '{ print $2; }' | sed 's@/.*@@')"
     local url="http://${docker_ip}:8080/api"
     local n=60
-    while true; do
-      if curl -s "${url}" >&/dev/null; then
-        break
-      fi
+    while ! curl -s "${url}" >&/dev/null; do
       if ((--n == 0)); then
         echo "Error: timed out waiting for apiserver to become available" >&2
       fi
